-- ==============================================================================
-- EcoWise Supabase Database Schema Initialization
-- ==============================================================================
-- Description: Creates the 4 required tables for EcoWise (user_table, product_table,
-- challenge_progress_table, reward_table) with matching camelCase column names
-- and sets up Row Level Security (RLS) policies for anon access.
-- ==============================================================================

-- 1. Create user_table
CREATE TABLE IF NOT EXISTS public.user_table (
    "id" TEXT PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL DEFAULT '',
    "profilePictureUrl" TEXT,
    "isGoogleAccount" BOOLEAN NOT NULL DEFAULT FALSE,
    "ecoPoints" INTEGER NOT NULL DEFAULT 0,
    "productsAnalysed" INTEGER NOT NULL DEFAULT 0,
    "challengesCompleted" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast email lookup (case-insensitive)
CREATE INDEX IF NOT EXISTS idx_user_table_email ON public.user_table (LOWER("email"));

-- 2. Create product_table
CREATE TABLE IF NOT EXISTS public.product_table (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "brand" TEXT NOT NULL DEFAULT '',
    "category" TEXT NOT NULL DEFAULT '',
    "weightSize" TEXT NOT NULL DEFAULT '',
    "packagingMaterial" TEXT NOT NULL DEFAULT '',
    "isOrganic" BOOLEAN NOT NULL DEFAULT FALSE,
    "ecoScore" INTEGER NOT NULL DEFAULT 0,
    "carbonFootprint" TEXT NOT NULL DEFAULT '',
    "recyclability" TEXT NOT NULL DEFAULT '',
    "visualType" TEXT NOT NULL DEFAULT '',
    "createdAt" BIGINT NOT NULL DEFAULT 0,
    "isFavorite" BOOLEAN NOT NULL DEFAULT FALSE,
    "isRecyclingActivity" BOOLEAN NOT NULL DEFAULT FALSE,
    "centreName" TEXT,
    "centreAddress" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION
);

-- Index for product lookup by userId
CREATE INDEX IF NOT EXISTS idx_product_table_userId ON public.product_table ("userId");

-- 3. Create challenge_progress_table
CREATE TABLE IF NOT EXISTS public.challenge_progress_table (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "challengeId" TEXT NOT NULL,
    "challengeTitle" TEXT NOT NULL,
    "imagePath" TEXT NOT NULL DEFAULT '',
    "submissionDate" TEXT NOT NULL,
    "timestamp" BIGINT NOT NULL DEFAULT 0
);

-- Index for challenge progress lookup by userId
CREATE INDEX IF NOT EXISTS idx_challenge_progress_table_userId ON public.challenge_progress_table ("userId");

-- 4. Create reward_table
CREATE TABLE IF NOT EXISTS public.reward_table (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "dateFormatted" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Active'
);

-- Index for reward lookup by userId
CREATE INDEX IF NOT EXISTS idx_reward_table_userId ON public.reward_table ("userId");

-- ==============================================================================
-- Row Level Security (RLS) Configuration
-- Enable RLS and grant anon / authenticated full access for mobile app operations
-- ==============================================================================

-- Enable RLS
ALTER TABLE public.user_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_progress_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_table ENABLE ROW LEVEL SECURITY;

-- Allow anon and authenticated roles full read/write access to user_table
DROP POLICY IF EXISTS "Allow anon all on user_table" ON public.user_table;
CREATE POLICY "Allow anon all on user_table"
    ON public.user_table
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anon and authenticated roles full read/write access to product_table
DROP POLICY IF EXISTS "Allow anon all on product_table" ON public.product_table;
CREATE POLICY "Allow anon all on product_table"
    ON public.product_table
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anon and authenticated roles full read/write access to challenge_progress_table
DROP POLICY IF EXISTS "Allow anon all on challenge_progress_table" ON public.challenge_progress_table;
CREATE POLICY "Allow anon all on challenge_progress_table"
    ON public.challenge_progress_table
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anon and authenticated roles full read/write access to reward_table
DROP POLICY IF EXISTS "Allow anon all on reward_table" ON public.reward_table;
CREATE POLICY "Allow anon all on reward_table"
    ON public.reward_table
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);
